config/routes.rb
Tickets::Application.routes.draw do
  post '/' => 'tickets#create'

  get '/admin' => 'tickets#index'

  root 'tickets#show', as: 'ticket'

  resources :tickets, path: '', only: [:index, :create, :destroy] do
    collection do
      get 'destroy_all'
    end
  end

end

app/controllers/tickets_controller.rb
# Manages Tickets and their public HTML interfaces.
class TicketsController < ApplicationController
  before_filter :authenticate, only: [:index, :destroy_all]

  respond_to :html

  # Lists all Tickets in the database. Requires authentication.
  #
  # GET /admin
  #
  # @return [String] the HTML for the Ticket list (which is also the admin page)
  def index
    @tickets = Ticket.all
  end

  # Shows a user's Ticket. If the user does not have a Ticket open, it lets the
  # user create a new one.
  #
  # GET /
  #
  # @return [String] the HTML for the Ticket (or the new Ticket page)
  def show
    unless @ticket = Ticket.where(computer: session[:computer]).first
      @ticket = Ticket.new name: session[:name], computer: session[:computer]
      render 'new'
    end
  end

  # Creates and saves a new Ticket. If the Ticket is invalid, it lets the user
  # create a new Ticket.
  #
  # POST /
  #
  # @return [String] the HTML for the newly saved Ticket (or the new Ticket
  #   page)
  def create
    @ticket = Ticket.new ticket_params

    respond_to do |format|
      if @ticket.save
        session[:name] = @ticket.name
        session[:computer] = @ticket.computer
        format.html { redirect_to @ticket }
      else
        format.html { render 'new' }
      end
    end
  end

  # Destroys a Ticket from the database (if it's in the database).
  #
  # DELETE /1
  #
  # @return [String] a redirect to the previous page (or / if there were none)
  def destroy
    @ticket = Ticket.find params[:id]
    @ticket.destroy
  rescue ActiveRecord::RecordNotFound
  ensure
    redirect_to(request.referer || ticket_path)
  end

  # Destroys all Tickets from the database. Requires authentication.
  #
  # GET /destroy_all
  #
  # @return [String] a redirect to the previous page (or / if there were none)
  def destroy_all
    # Note: It is preferred to use delete_all instead of destroy_all here.
    # destroy_all has to instantiate and destroy every Ticket individually,
    # which is very expensive.
    Ticket.delete_all

    redirect_to(request.referer || ticket_path)
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def ticket_params
    params.require(:ticket).permit(:name, :computer, :reason)
  end

end

app/views/layouts/application.html.haml
!!!
%html{lang: 'en'}

  %head
    %meta{charset: 'utf-8'}/
    / basic info
    %title Tickets - #{yield :title}
    %meta{content: 'width=device-width, initial-scale=1.0', name: 'viewport'}/
    / css
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    / meta tags
    = csrf_meta_tags
    / icons
    %link{href: '/favicon.png', rel: 'icon'}/

  %body

    #main.container

      .page-header
        %h1

          / app and page title
          Tickets
          %small= yield :title

          / extra UI buttons for the page
          .pull-right
            = yield :extra_buttons
            - if current_page? tickets_path
              = link_to ticket_path, class: 'btn btn-default' do
                %span.glyphicon.glyphicon-home
                Home
            - else
              = link_to tickets_path, class: 'btn btn-default' do
                %span.glyphicon.glyphicon-th-list
                Admin

      / page content
      = yield

    / scripts
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    /[if lt IE 9] <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>

app/views/tickets/index.html.haml
- content_for :title, 'Admin'
- content_for :extra_buttons do
  = button_to destroy_all_tickets_path, method: 'get', class: 'btn btn-danger', 'data-confirm' => 'Are you sure?', rel: 'nofollow' do
    %span.glyphicon.glyphicon-remove
    Destroy all

%table.table.table-striped.table-bordered.table-hover.table-condensed

  / header of the table
  %tr
    %th #
    %th Name
    %th Computer
    %th Reason
    %th Created

  - if @tickets.length > 0
    / body of the table
    = render @tickets
  - else
    / displayed if no tickets are open
    %tr
      %td.text-muted{colspan: '4'} No tickets are open.

app/views/tickets/show.html.haml
- content_for :title, 'Your ticket'
- content_for :extra_buttons do
  = button_to @ticket, method: :delete, class: 'btn btn-danger' do
    %span.glyphicon.glyphicon-remove
    Destroy

/ show names and values of the Ticket's attributes
%dl.dl-horizontal

  %dt Name
  %dd= @ticket.name

  %dt Computer
  %dd= @ticket.computer

  %dt Reason
  %dd= @ticket.reason

  %hr

  %dt Created
  %dd #{time_ago_in_words @ticket.created_at} ago

  %dt Position
  %dd= @ticket.position.ordinalize